# Generated by Django 4.2.6 on 2024-03-16 16:08

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "new_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("support_email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("about_us", models.TextField()),
                ("telegram", models.CharField(blank=True, max_length=100, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "is_manager",
                    models.BooleanField(default=False, verbose_name="Manager"),
                ),
                ("is_client", models.BooleanField(default=True, verbose_name="Client")),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WithdrawalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_withdraw", models.BooleanField(default=False)),
                (
                    "message",
                    models.CharField(default="Please Contact Support.", max_length=200),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_currency", models.CharField(max_length=10)),
                ("wallet_withdraw", models.CharField(max_length=20)),
                ("comment", models.CharField(max_length=50, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KYC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("government_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("birthdate", models.DateField()),
                ("id_front", models.ImageField(upload_to="SVEX_APP/static/kyc/")),
                ("id_back", models.ImageField(upload_to="SVEX_APP/static/kyc/")),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "btc_deposit_wallet",
                    models.CharField(default="wallet", max_length=100),
                ),
                (
                    "eth_deposit_wallet",
                    models.CharField(default="wallet", max_length=100),
                ),
                (
                    "erc20_deposit_wallet",
                    models.CharField(default="wallet", max_length=100),
                ),
                (
                    "trc20_deposit_wallet",
                    models.CharField(default="wallet", max_length=100),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_currency", models.CharField(max_length=10)),
                ("wallet_withdraw", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotbtc_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "btc_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "eth_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "usdt_balance_erc20",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "usd_balance_trc20",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "client",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_number", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                (
                    "client_credits",
                    models.DecimalField(decimal_places=2, default=10, max_digits=10),
                ),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=100, unique=True)),
                (
                    "case_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bug", "Bug Report"),
                            ("Feature", "Feature Request"),
                            ("Complaint", "Customer Complaint"),
                            ("Refund", "Refund Request"),
                            ("Account", "Account Issue"),
                            ("Security", "Security Concern"),
                            ("Transaction", "Transaction Issue"),
                            ("Wallet", "Wallet Management Issue"),
                            ("Exchange", "Exchange Rate Discrepancy"),
                            ("KYC", "Know Your Customer (KYC) Issue"),
                            ("AML", "Anti-Money Laundering (AML) Issue"),
                            ("Withdrawal", "Withdrawal Problem"),
                            ("Deposit", "Deposit Issue"),
                            ("Trading", "Trading Issue"),
                            ("API", "API Integration Issue"),
                            ("Chart", "Charting/Graphical Issue"),
                            ("Order", "Order Execution Issue"),
                            ("Liquidity", "Liquidity Problem"),
                            ("Margin", "Margin Trading Issue"),
                            ("Funds", "Funds Availability Issue"),
                            ("Verification", "Account Verification Issue"),
                            ("Scam", "Suspected Scam/Phishing Report"),
                            ("Tax", "Tax Reporting Issue"),
                            ("Regulatory", "Regulatory Compliance Issue"),
                            ("Privacy", "Privacy Concern"),
                            ("Support", "Customer Support Request"),
                            ("Education", "Education/Training Request"),
                            ("Feedback", "General Feedback"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client_contact_details", models.CharField(max_length=255)),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Responded", "Responded"),
                            ("Escalated", "Escalated"),
                            ("On Hold", "On Hold"),
                            ("Closed-Resolved", "Closed-Resolved"),
                            ("Closed-NotResolved", "Closed-NotResolved"),
                            ("Closed-Spam", "Closed-Spam"),
                            ("Closed-Lost", "Closed-Lost"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("case_subject", models.CharField(max_length=255)),
                (
                    "case_touch",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("First Touch", "First Touch"),
                            ("Second Touch", "Second Touch"),
                            ("Processing", "Processing"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "case_priority",
                    models.CharField(
                        choices=[
                            ("Very High", "Very High"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                            ("Very Low", "Very Low"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                ("case_notes", models.TextField(blank=True, null=True)),
                ("case_created_at", models.DateTimeField(auto_now_add=True)),
                ("case_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="case_attachments/"
                    ),
                ),
                ("case_resolution_details", models.TextField(blank=True, null=True)),
                ("customer_feedback", models.TextField(blank=True, null=True)),
                (
                    "case_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_cases",
                    models.ManyToManyField(blank=True, to="SVEX_APP.case"),
                ),
            ],
        ),
    ]
