# Generated by Django 5.0.4 on 2024-08-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SVEX_APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="id_back",
            field=models.ImageField(upload_to="kyc/"),
        ),
        migrations.AlterField(
            model_name="kyc",
            name="id_front",
            field=models.ImageField(upload_to="kyc/"),
        ),
    ]
