# Generated by Django 5.0.4 on 2024-08-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SVEX_APP", "0002_alter_kyc_id_back_alter_kyc_id_front"),
    ]

    operations = [
        migrations.AddField(
            model_name="kyc",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
