# Generated by Django 5.0.4 on 2024-08-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SVEX_APP", "0003_kyc_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kyc",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
