# Generated by Django 5.0.4 on 2024-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SVEX_APP", "0004_alter_kyc_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_notes",
            field=models.TextField(default="Waiting for response."),
        ),
    ]
