# Generated by Django 5.2.7 on 2025-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SVEX_APP", "0005_alter_case_case_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientwallet",
            name="btc_balance",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clientwallet",
            name="eth_balance",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clientwallet",
            name="spotbtc_balance",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clientwallet",
            name="usd_balance_trc20",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clientwallet",
            name="usdt_balance_erc20",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="amount",
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
