# Generated by Django 5.2.7 on 2025-11-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SVEX_APP", "0006_alter_clientwallet_btc_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientwallet",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=42, unique=True, null=True),
        ),
    ]
