# Generated by Django 5.2.7 on 2026-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SVEX_APP", "0007_clientwallet_wallet_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="withdrawal",
            name="wallet_withdraw",
            field=models.CharField(max_length=100),
        ),
    ]
